### PR TITLE
general fixes for arabic content and empty responses

### PR DESCRIPTION
**Pull request by rafapolo**
fixes:
- right-to-left posts
- empty iframes
- no images
- empty http resposes

### CODE REVIEW

**Review by zhgchgli0718 — APPROVED** [review]
thanks for your contribution

**Comment by rafapolo** [comment]
missing unit tests, sorry. but just with these changes I finally managed to fully scrap >3k posts now at https://github.com/rafapolo/AreYouSyrious

**Comment by rafapolo** [comment]
also did a small script to generate the README.md linking to all scrapped posts https://github.com/rafapolo/AreYouSyrious/blob/posts/index.rb

**Comment by zhgchgli0718** [comment]
it's okay, because I didn't write testing in this project either, I'm not a professional Ruby Developer 😅

**Comment by zhgchgli0718** [comment]
> missing unit tests, sorry. but just with these changes I finally managed to fully scrap >3k posts now at https://github.com/rafapolo/AreYouSyrious

thanks for the contribution & using this tools!
it's very pleased to see this tools has successful help you to backup your medium posts :).

**Pull request merged**
